### ISSUE TITLE
support osxfuse?

### ISSUE THREAD

**Issue by josephholsten** [rpodgorny/unionfs-fuse#1]
I'm guessing I'm hitting something obvious, but I don't know how to proceed.

```
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src/
cc -Wall -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse  -DFUSE_USE_VERSION=26 -DLIBC_XATTR   -c -o unionfs.o unionfs.c
unionfs.c:291:14: error: use of undeclared identifier 'FUSE_IOCTL_COMPAT'
        if (flags & FUSE_IOCTL_COMPAT)
                    ^
unionfs.c:306:30: warning: implicit declaration of function '_IOC_SIZE' is invalid in C99 [-Wimplicit-function-declaration]
                set_debug_path(debug_path, _IOC_SIZE(cmd));
                                           ^
unionfs.c:870:3: error: field designator 'ioctl' does not refer to any field in type 'struct fuse_operations'
        .ioctl = unionfs_ioctl,
         ^
1 warning and 2 errors generated.
make[1]: *** [unionfs.o] Error 1
make: *** [build] Error 2
```

**Comment by rpodgorny** [comment]
looks like there's an include missing or you're using some old version of fuse.

unfortunately, i don't have any osx machine to investigate this on. :-(

**Comment by wouterlucas** [comment]
I had the same issue with installing osxfuse directly from the dmg. If you build osxfuse from source and install it, the fuse_common.h file does include FUSE_IOCTL_COMPAT. Dunno why there is a difference.

**Comment by rpodgorny** [comment]
where does this dmg come from?

anyway, this looks like a osxfuse's bug, not unionfs-fuse's, right?

**Comment by wouterlucas** [comment]
I previously installed it from: https://osxfuse.github.io/

And no, its related to the header files that come with osxfuse. Once you get the right header files by compiling osxfuse from source unionfs-fuse continues without the error above. Although I did ran into another problem on my 64 bit mac, I'll create a separate issue for that (got around it by commenting it out for now).

**Comment by rpodgorny** [comment]
ok. so i'm closing this and please be sure to file an issue report on osxfuse.

thanks for finding the source of the problem!
