### ISSUE TITLE
Man page "unionfs" speaking of "unionfs-fuse"

### ISSUE THREAD

**Issue by hartwork** [rpodgorny/unionfs-fuse#10]
The unionfs man page seems to say "unionfs-fuse" where I would expect "unionfs", consistently.

**Comment by rpodgorny** [comment]
fixed one case.

as for the others, the "-fuse" is there to denote it's userspace based implementation (there's also a unionfs kernel module - i don't want any confusion).

of course, i might have missed something, feel free to reopen/comment.
