### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by TheKnarf** [rpodgorny/unionfs-fuse#103]
I'd like to test this out, but how do I set it up?

Would be nice if the readme had some setup instructions.

**Comment by TheKnarf** [comment]
When cloning the repository on MacOS and trying to run `make` I get the following error:

```
$ make
/Library/Developer/CommandLineTools/usr/bin/make -C src/
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o unionfs.o unionfs.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o fuse_ops.o fuse_ops.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o opts.o opts.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o debug.o debug.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o findbranch.o findbranch.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o readdir.o readdir.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o general.o general.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o unlink.o unlink.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o rmdir.o rmdir.c
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o cow.o cow.c
In file included from cow.c:24:
./cow_utils.h:11:9: warning: 'MAXBSIZE' macro redefined [-Wmacro-redefined]
#define MAXBSIZE 4096
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/param.h:181:9: note: previous definition is here
#define MAXBSIZE        (256 * 4096)
        ^
1 warning generated.
cc -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -DFUSE_USE_VERSION=29 -DLIBC_XATTR   -c -o cow_utils.o cow_utils.c
cow_utils.c:68:14: error: no member named 'st_atim' in 'struct stat'
        ut[0] = fs->st_atim;
                ~~  ^
cow_utils.c:69:14: error: no member named 'st_mtim' in 'struct stat'
        ut[1] = fs->st_mtim;
                ~~  ^
2 errors generated.
make[1]: *** [cow_utils.o] Error 1
```

**Comment by rpodgorny** [comment]
hmm, since this does not seem to be an isolated case, i will try to investigate soon

**Comment by TheKnarf** [comment]
Feel like this issue should be reopned. It's not only the actual build problems on MacOS, but for other OS's as well would it be interesting to see how we're supposed to build and use this.

Are we supposed to run `make` in the repo, or something like:

```
mkdir build
cd build
cmake ..
make
```

It's a bit weird that there's both a Makefile and a CMakeLists.txt in the repo... and no documentation on what we're supposed to use.

**Comment by rpodgorny** [comment]
i've updated the readme - is it somewhat clearer now...?

**Comment by TheKnarf** [comment]
> i've updated the readme - is it somewhat clearer now...?

That is better :-)

Still would have liked some info on what we need to install on the system to have a working build enviroment. Something like `brew install macfuse` for MacOS perhaps? And similare instructions for Linux.

**Comment by rpodgorny** [comment]
https://github.com/rpodgorny/unionfs-fuse/issues/86

**Comment by rpodgorny** [comment]
> > i've updated the readme - is it somewhat clearer now...?
> 
> That is better :-)
> 
> Still would have liked some info on what we needs to be installed on the system to have a working build environment. Something like `brew install macfuse` for MacOS perhaps? And similare instructions for Linux.

could you please submit a pull request with build instructions for macos? i'll use it as a base for more thorough build instructions...

**Comment by rpodgorny** [comment]
this should be solved in the upcoming release. please test the current master branch if you find some time, thanks...

https://github.com/rpodgorny/unionfs-fuse/issues/110

**Comment by rpodgorny** [comment]
version 3.0 is out with much better documentation. if you have more contribute, please open another issue of pull request. thanks!
