### ISSUE TITLE
Link and image for Gratipay is broken

### ISSUE THREAD

**Issue by TheKnarf** [rpodgorny/unionfs-fuse#106]
<img width="233" alt="Screenshot 2021-12-27 at 16 05 57" src="https://user-images.githubusercontent.com/213777/147483971-9e894c95-dd31-45a4-8514-bda1102aea75.png">

The image and link for "Gratipay" in the Readme is broken.

**Comment by rpodgorny** [comment]
thanks! ...changed to liberapay...
