### ISSUE TITLE
release 3.0

### ISSUE THREAD

**Issue by rpodgorny** [rpodgorny/unionfs-fuse#110]
this is a meta-bug to track the issue of next version

i'm going to release version 3.0 soon. it has improved cmake build flow (should work on macos and linux) and some other goodies. also, it links to libfuse3 by default.

feel free to voice any concerns here.

**Comment by rpodgorny** [comment]
@aakefbs @normanr @TheKnarf

**Comment by rpodgorny** [comment]
also, i'm considering a licence change - something copyleft (gpl?)... ...after i've spent several hours fighting with macos and experienced the result of what happens when a greedy company takes a bsd-licenced code and creates a closed-source opaque monstrosity - without ever contributing anything back - i kind of don't like the idea of bsd licence any more... :-(

**Comment by WaterJuice** [comment]
> also, i'm considering a licence change - something copyleft (gpl?)... ...after i've spent several hours fighting with macos and experienced the result of what happens when a greedy company takes a bsd-licenced code and creates a closed-source opaque monstrosity - without ever contributing anything back - i kind of don't like the idea of bsd licence any more... :-(

It would be a shame to put a more restrictive license like the gpl3 on it. It can really limit the use of a product by trainting anything it comes near.
In terms of Apple never contributing anything back, I wouldn't say that was necessarily true. They have contributed a bunch of things back to the clang project. True not as much as they could, and they don't open source the Xcode compiler.

**Comment by rpodgorny** [comment]
version 3.0 is out
