### ISSUE TITLE
COW Baseline Feature

### ISSUE THREAD

**Issue by JavaScriptDude** [rpodgorny/unionfs-fuse#132]
Could a feature be added to allow a path be added which would store a copy of the original file at the point before a copy-on-write is saved to the `unionfs-fuse` `mount_point`.

The rule would be that the `--cow_base` directory would be a writable directory and the system should not allow clobbering of files; a failure mode which should not happen if used correctly.

My usecase would allow me to use `unionfs-fuse` as a light weight development branch system where the `--cow_base` directory contains the 'branched' baseline version, the `RO` source directory would be the SVC Trunk and the `RW` directory would be the change request folder, representing only the files being changed in the change request. 

Note: A change request is a uniquely numbered folder which contains a bundle of all changes to one or more systems / apps to be deployed at some future date and would contain baseline copies of modified files from the SVC Trunk.

**Comment by rpodgorny** [comment]
hi! this sounds like being out of scope of the intended functionality so i'm quite hesitant to consider this. :-(

...anyway, i don't know your exact use case but i'd suspect something like this may work:
1) mkdir ro; mkdir rw; mkdir union
2) mount ro,rw -> union
3) do your work
4) execute "find rw" and replace "rw" with "ro" in the list
5) remove list items which do not name an existing file
6) ...profit! now you have a list of files which must have been copied

**Comment by JavaScriptDude** [comment]
Understood. Thanks for the comments. 

My usecase is quite specific to my development workflows and would save me a ton of time. I'll do a fork in the future when I have time to wrap my head around learning a new language. Been a long time since I wrote any C.

**Comment by JavaScriptDude** [comment]
BTW - Love this super useful tool. Thanks for maintaining it!

**Comment by JavaScriptDude** [comment]
FYI - I created a hard fork of this project to implement my usecases: [unionfs-fuse-jsd](https://github.com/JavaScriptDude/unionfs-fuse-jsd)

It works like a charm for my devops tools.
