### ISSUE TITLE
Changes introduced by `69a34a4` cause wine to hang forever

### ISSUE THREAD

**Issue by ruanformigoni** [rpodgorny/unionfs-fuse#133]
Hello there! I use `unionfs-fuse` in my project [gameimage](https://gitlab.com/formigoni/gameimage). Yesterday I've noticed an issue that most times, wine hangs forever on startup, and after further investigation saw that the project was updated.

 If I use:
```sh
# Reset to the commit previous to 69a34a4
git reset --hard 3346a83fbaeee928490924f271dde1eab2acbf48
``` 

The problem is solved.

**Comment by bsbernd** [comment]
@rpodgorny I don't think there is 'simple' fix for logging, except of totally disabling it for now. Simple changes just make it worse :(

**Comment by rpodgorny** [comment]
wow! thanks for spotting (and reporting) this! ...it must have slipped my testing. but now i'm able to preproduce - will investigate further...

**Comment by rpodgorny** [comment]
> @rpodgorny I don't think there is 'simple' fix for logging, except of totally disabling it for now. Simple changes just make it worse :(

hmmm, ok, acknowledged... :-(

**Comment by bsbernd** [comment]
I created a pull request for that. I will really try to find some time for unionfs, but I'm not using it myself for the moment and really busy with other projects :/
