### ISSUE TITLE
[3.4] Failing to compile with error `fuse: off_t must be 64bit` on 32bit x86

### ISSUE THREAD

**Issue by hartwork** [rpodgorny/unionfs-fuse#142]
Hi!

it was [brought to my attention](https://bugs.gentoo.org/928360) that unionfs-fuse 3.4 fails to compile on 32bit x86 saying:

```
In file included from /usr/include/fuse3/fuse.h:19,
                 from unionfs.c:13:
/usr/include/fuse3/fuse_common.h:938:1: error: static assertion failed: "fuse: off_t must be 64bit"
  938 | _Static_assert(sizeof(off_t) == 8, "fuse: off_t must be 64bit");
      | ^~~~~~~~~~~~~~
```

There is note…

>  On 32bit systems please add -D_FILE_OFFSET_BITS=64 to your compile flags!

… at https://github.com/libfuse/libfuse/blob/20de66dc898002b9315192a5095a3dcd4f6ec248/include/fuse_common.h#L963 . Could that be added to the unionfs-fuse build system conditionally or unconditionally? I have seen https://github.com/moosefs/moosefs/commit/9299480caabe37ef51e8c349e2ea94ee2d339295 fix it like that, the related issue there is https://github.com/moosefs/moosefs/issues/311 . Would a pull request doing something like that be welcome, if I find time to do one?

Best, Sebastian

**Comment by rpodgorny** [comment]
hi! can you try current master? if it works for you, i'll cut a release...

**Comment by hartwork** [comment]
Hi @rpodgorny, thanks for 4a2ce5c225eaa3e49c26569613a33d914c59a33a!

Of the two builds systems, I was able to test the `src/Makefile` on using `make CFLAGS=-m32 -C src/` on my 64bit box and the assertion failed before and did not fail after, so that's good. For the CMake build system, I could not make the unfixed build fail, I tried `CFLAGS=-m32` and `-DCMAKE_CXX_FLAGS=-m32` and deleting `CMakeCache.txt` but neither worked or even seemed to show any effect that I could observe with `make VERBOSE=1`. Any ideas?

PS: Would you be open to a pull request adding GitHub Actions CI for Linux? With Travis CI gone, the project seems to be without any CI and so any pull request could break the build and not even be noticed.

**Comment by hartwork** [comment]
@rpodgorny PS: I think I know now: `SET(CMAKE_C_FLAGS ...)` is overriding any user `CFLAGS`. That should probably be changed, e.g. Gentoo would need to patch support for user build flags in (but happens to not use the CMake build system at the moment but the makefile). Are you open for that to change?

**Comment by rpodgorny** [comment]
@hartwork yes and yes. if you have time and mood to add some github action to test builds, i'll graldly merge it. also, if you have any fixes for cmake files, feel free to open a pull request. cmake is still not the "official" way of building unionfs-fuse - i started to experiment with it long time ago but never actually finished the move so it's not really a priority.

**Comment by hartwork** [comment]
@rpodgorny encouraged by those words I have build pull request #145 now. I'm looking forward to your review :pray:

**Comment by rpodgorny** [comment]
@hartwork is there a 32bit image for github actions we could use to test this?

**Comment by hartwork** [comment]
> @hartwork is there a 32bit image for github actions we could use to test this?

@rpodgorny I believe that:
- the short answer is "no"
- using `-m32` and compiling both FUSE and unionfs with that may work on an x86_64 host

**Comment by rpodgorny** [comment]
> > @hartwork is there a 32bit image for github actions we could use to test this?
> 
> @rpodgorny I believe that:
> 
>     * the short answer is "no"
> 
>     * using `-m32` and compiling both FUSE and unionfs with that may work on an x86_64 host

yeah, i thought so. thanks for the confirmation. ...are you still having problems compiling current master on your 32bit system?

**Comment by hartwork** [comment]
> ...are you still having problems compiling current master on your 32bit system?

@rpodgorny all my own boxes are am64 by now, issue https://bugs.gentoo.org/928360 was by someone else but since I maintain the package in Gentoo… Making the CI cover `-m32` would be a good regression test though to keep x86 alive as long as needed.

**Comment by rpodgorny** [comment]
> > ...are you still having problems compiling current master on your 32bit system?
> 
> @rpodgorny all my own boxes are am64 by now, issue https://bugs.gentoo.org/928360 was by someone else but since I maintain the package in Gentoo… Making the CI cover `-m32` would be a good regression test though to keep x86 alive as long as needed.

well, since most of the distros are discontinuing 32bit support (and all my boxes are 64bit are as well), i don't want to spend too much time on this. i'm closing this hoping that my patch to enable -D_FILE_OFFSET_BITS=64 unconditionally fixes the issue.

if you feel like adding -m32 to the ci, i'll be happy to accept it! but generally, i don't consider that to be a priority.
