### ISSUE TITLE
Is there an official source for centos 7?

### ISSUE THREAD

**Issue by zh324** [rpodgorny/unionfs-fuse#144]
Hi I googled official source of unionfs-fuse but only found this third party source: https://rhel.pkgs.org/7/okey-x86_64/fuse-unionfs-0.26-2.el7.centos.x86_64.rpm.html
Is there an official source for centos7? Thanks!

**Comment by rpodgorny** [comment]
hi, do you mean official binary package source? no, i only have resources to do source-only releases so it's up to distro's packagers to do the build/package/distribute step.

i'm not particulary familiar with centos but if there's need to provide binary packages, i'm willing to accept patches that would build them using some kind of ci (github actions?).

**Comment by zh324** [comment]
Yes I mean binary packages. Yeah let me try if I can build this...

**Comment by zh324** [comment]
I was able to make and install the package. However when using it, there's below error:

```
$ /usr/local/bin/unionfs upper=RW:lower=RO merged_1 -o cow,allow_other,default_permissions
fuse: warning: library too old, some operations may not not work
fuse: unknown option(s): `-o big_writes'
```

Wondering what might be the cause?  By running --version I got following:\

```
$ /usr/local/bin/unionfs --version
unionfs-fuse version: 3.4
(compiled with xattr support)
FUSE library version 3.6.1
using FUSE kernel interface version 7.29
fusermount3 version: 3.6.1
```
Thanks in advance!

**Comment by zh324** [comment]
Looks like turning off option(WITH_LIBFUSE3 "Enable libfuse3 support") solves the issue..

**Comment by bsbernd** [comment]
Well, there is no problem, libfuse3 has removed the big_writes option and enabled it by default.

**Comment by zh324** [comment]
Close this ticket
