### ISSUE TITLE
debian/source/version '3.0 (quilt)' missing

### ISSUE THREAD

**Issue by strarsis** [rpodgorny/unionfs-fuse#16]
Not sure whether it is good practice or possible to fix this on an existing release tag - 
but debian/source/version with '3.0 (quilt)' is required for a git repository,
otherwise debuild -S won't build the source package with .git;.git/**/* untracked.

**Comment by rpodgorny** [comment]
solved by removed distro-specific (debian) stuff altogether. ;-)
