### ISSUE TITLE
Separate debian/<codename> branches / Jessie dependencies

### ISSUE THREAD

**Issue by strarsis** [rpodgorny/unionfs-fuse#18]
Debian Package 'fuse-utils' up to Debian Wheezy has been removed' in Debian Jessie, 
unionfs-fuse should now depend directly on package 'fuse' instead.
https://packages.debian.org/de/wheezy/fuse-utils
https://packages.debian.org/de/jessie/fuse

For future-proof support of coming Debian releases, 
the 'debian/' directory and Debian-specific modifications 
should go into separate 'debian/<codename>' branches:
'debian/wheezy' with debian/control with Dependency 'fuse-utils'  and 
'debian/jessie' with debian/control with Dependency 'fuse'.

Thank you and 
with best regards

**Comment by rpodgorny** [comment]
solved by removed distro-specific (debian) stuff altogether. ;-)
