### ISSUE TITLE
Please make a new release (0.27?) some time soon

### ISSUE THREAD

**Issue by hartwork** [rpodgorny/unionfs-fuse#3]
The latest release 0.26 is of 2012-09-11. Since then, one and a half pages of commits happened in the Git repository that do not end up downstream (Linux distributions, users) without a release.
Are there plans for a new release some time soon? How "releasable" is master branch as of today?
Thanks and best, Sebastian

**Comment by rpodgorny** [comment]
huh, sorry for replying so late, i had no idea i had to watch my own repositories on github. ;-)

i'll take a look at this, soon.

**Comment by hartwork** [comment]
Great to hear from you, sounds good!

**Comment by rpodgorny** [comment]
the 1.0 release is coming soon. please test the current master if you can/want.

**Comment by hartwork** [comment]
For any Gentoo users wishing to test straight from Git there is a live ebuild now:
```
# sudo sh -c 'echo "sys-fs/unionfs-fuse **" >> /etc/portage/package.keywords/sys-fs--unionfs-fuse'
# sudo emerge -1av sys-fs/unionfs-fuse
```

**Comment by hartwork** [comment]
Looks like there is a 1.0 release by now. Excellent! Closing...
