### ISSUE TITLE
Add DUMP branches

### ISSUE THREAD

**Issue by Caagr98** [rpodgorny/unionfs-fuse#45]
The current functionality is like this:
```
$ unionfs rw=RW:ro=RO uni
├── ro/
│   └── foo/
├── rw/
└── uni/
    └── foo/
$ touch uni/bar
├── ro/
│   └── foo/
├── rw/
│   └── bar
└── uni/
    ├── bar
    └── foo/
$ touch uni/foo/bar
touch: cannot touch ‘uni/foo/bar’: Permission denied
```
This is undesirable if you, for example, want to have one shared (RO) folder containing a game, and union it with another (RW) folder to store its save data in, to keep the game and data separate.

I suggest adding a third mode in addition to RO and RW. I'll call it DUMP, even though that is a silly name.

If there exists a branch with the DUMP mode, all files would be written to that branch. Multiple DUMP branches would be invalid. If the written file's directory doesn't exist in the DUMP branch, but that directory exists in another branch, the directory would be created in the DUMP branch. If the directory doesn't exist in any branch, writing to it would result in the standard that-directory-doesn't-exist error (which I think is ENOENT, but I'm not sure).

----

This should probably be marked as an ENHANCEMENT issue, but I don't know how to do that.

**Comment by aakefbs** [comment]
Missing "-ocow"?

**Comment by Caagr98** [comment]
Yeah, seems so. Now I feel dumb.

**Comment by rpodgorny** [comment]
@Caagr98, please, never ever feel dumb for asking a legitimate question!

@aakefbs, thanks for the answer!
