### ISSUE TITLE
Makefile: Tries to install missing src/unionfs?

### ISSUE THREAD

**Issue by hartwork** [rpodgorny/unionfs-fuse#5]
Hi!
`make install` failes with
```
install: cannot stat ‘src/unionfs’: No such file or directory
```
over here. In the master Makefile I read
```
install -m 0755 src/unionfs $(DESTDIR)$(PREFIX)$(BINDIR)
```
After compilation, these are the executables I find:
```
# find -type f -executable
./test.sh
./test.py
./src/unionfs-fuse
./src/unionfs-fuse-ctl
./mount.unionfs-fuse
./examples/unionfs-fuse-nfs-root
./examples/rc.local.omit-pid.sh
./examples/S01a-unionfs-fuse-live-cd.sh
./debian/rules
```
So I wonder:
* Is `src/unionfs` supposed to be `src/unionfs-fuse`
* What is `src/unionfs-fuse-ctl` and why is it not installed?

**Comment by rpodgorny** [comment]
ha! thanks for spotting this.

i've been renaming the binaries to avoid collisions with other unionfs implementations and forgot this.

anyway, i might be returning to the original name (plain unionfs) as there seem to be no other alternatives. ;-) (the unionfs-fuse name has been an exception for debian - it seems even debian doesn't need this so i'll probably gravitate to plain unionfs).

the unionfs-fuse-ctl is a ioctl based tool to communicate with the running unionfs instance. currently, it only supports playing with the debug stuff. not installing it is a bug and thanks for spotting that, too!

**Comment by hartwork** [comment]
Looks like your commit 6d40b30c9410a218f3e3724906bd921a7279a440 just fixed that. I guess the ticket can be close then already? It also fixed the live ebuild I'm just adding, very nice :)

**Comment by rpodgorny** [comment]
ok, so i've renamed everything back to unionfs and unionfsctl.
