### ISSUE TITLE
ownership changing

### ISSUE THREAD

**Issue by jxer** [rpodgorny/unionfs-fuse#53]
this is randomly happening on the mount, chown fixes it, but what the ????

only 2 mounts only 1 is rw other is ro

https://gyazo.com/0ef05a22ce9448c9d6173e3bcff9ba36

**Comment by jxer** [comment]
https://gyazo.com/75f6e6dff2372218ebda035a97076691

**Comment by rpodgorny** [comment]
hmmm, this looks too much like 1<<32 to be a coincidence... maybe some over/underflow?

**Comment by rpodgorny** [comment]
please specify the exact mount command, versions (unionfs-fuse, fuse, kernel) and the access method (this looks like windows screenshot - are you using samba? can you see the error on the machine itself using ls -l? etc...)

**Comment by jxer** [comment]
i don't believe its union anymore, i think the nfs mount v4 is getting overwhelmed, the issue is clearing up on its own when i throttle back on io, not sure what to do though its crashing programs, even with a ionice of c2 n7.
