### ISSUE TITLE
Using _DEFAULT_SOURCE to unlock chroot(2)

### ISSUE THREAD

**Issue by hartwork** [rpodgorny/unionfs-fuse#6]
Hi!
In Gentoo, a patch adding
```
// For chroot
#define _BSD_SOURCE
```
has been applied with previous releases of unionfs-fuse. The current code in Git reads
```
// For chroot
#define _DEFAULT_SOURCE 1
```
tough. In commit 593ed9bce4119af32ffb375eb3cdd3bac966b339 you write
> glibc 2.20 deprecates _BSD_SOURCE in favor of _DEFAULT_SOURCE

but I wonder about building against glibc alternatives or older versions of glibc. Are you sure everyone else handles _DEFAULT_SOURCE, too? When was it introduced and where?
Maybe it wouldn't hurt to define both to be on the safe side:
```
// For chroot
#define _DEFAULT_SOURCE 1
#define _BSD_SOURCE  // for glibc alternatives
```
What do you think?

**Comment by rpodgorny** [comment]
fixed in https://github.com/rpodgorny/unionfs-fuse/commit/c8dfa55eed6f5a9b1c38ff5601ae00c41f447fec
