### ISSUE TITLE
[Enhancement request:] Return PID of forked-off process

### ISSUE THREAD

**Issue by lvml** [rpodgorny/unionfs-fuse#68]
I was trying to implement a script that temporarily mounts a filesystem using unionfs. My problem with this is that I cannot find a method to reliably unmount this filesystem (from the same script) after use.

Using "umount" does not work (as it is not permitted for non-root users), sending the unionfs process a SIGTERM does work well, but the PID of that process I can only guess, and performing a "killall unionfs" is dangerous as other unionfs instances might be mounted by the same user at the same time.

Thus my enhancement request: Could you (e.g. if a certain command line option is present) just emit the PID of the process you fork off when mounting?

**Comment by aakefbs** [comment]
fusermount -u /path/to/mount

**Comment by pralaydak** [comment]
This shell function can kill the unionfs instance specific to your own mount point. Replace ${MNT} with your own mount point.

function do_unmount()
{
PID=`ps aux | grep ${MNT} | grep unionfs | grep -v grep | awk '{ print $2; }'`
if [ -n "${PID}" ]; then
kill -15 ${PID}
else
echo "Nothing to unmount"
fi
}

**Comment by rpodgorny** [comment]
i also recommend bernd's (aakefbs) method.
closing - feel free to reopen if this does not solve your problem.

**Comment by lvml** [comment]
@aakefbs: I cannot use `fusermount`, since this needs to have SUID privileges, and such I cannot set inside an AppImage (which is supposed to be useable without root privilege and bring along all the binaries required).

 @pralaydak: Your function proposal is probably much better than a "killall unionfs" scatter-shot, it does however require a lot of additional binaries (ps, grep, awk) that I either need to bring along statically linked or rely on being present on the target system. 

If "unionfs" was printing its forked-off PID, just "kill" would need to be present or supplied in the AppImage.

**Comment by rpodgorny** [comment]
hmmm, also, isn't there a way to keep the handle to the process and work with that? something like (pseudo-python):

```
p = subprocess.exec('unionfs -f /rw:/ro /union')  # this prevents unionfs from forking to background
subprocess.exec('do_something')
p.kill()
```

**Comment by lvml** [comment]
@rpodgorny: Interesting, this `-f` switch isn't mentioned in the source code I cloned from this git repository, and also not mentioned in the unionfs manpage. But it seems this option is inherited from libfuse, somehow.

So yes, starting unionfs with "-f" looks like a viable solution to me - thanks!
