### ISSUE TITLE
Files modified in read-only branch

### ISSUE THREAD

**Issue by rpodgorny** [rpodgorny/unionfs-fuse#7]
taken from email (6079.winston.smith@gmail.com):

```
Hi,

After using unionfs-fuse for some time, I've noticed that files are being modified on a read-only branch.

I have / mounted as read-only and a loop device mounted on /mnt/guest as read-write branch:

# /usr/bin/unionfs -o dev,suid -o cow /mnt/guest=RW:/=RO /mnt/union

I have discovered that write accesses to /mnt/guest modify files in /.

More specifically: After the mount, I've chrooted into /mnt/union:

# chroot /mnt/union

Then, I've compiled and installed gcc 4.9.1, including the man pages. The
ro-branch / has 4.5.1 installed. After exiting from the chroot, the man pages
of gcc are modified (and nothing else):

# exit
# ll /usr/man/man1/gcc.1
-rw-r--r--. 1 root root 974736 Aug 13 16:20 /usr/man/man1/gcc.1

I've discovered this because the permissions were first set to 0600, and a
non-root user couldn't do 'man gcc'. After resetting the permissions I've
noticed the file size and notable the file date (which could not be from
gcc 4.5.1).

The footer of the man page reveals the disaster:

man gcc
...
gcc-4.9.1                        2014-07-16                           GCC(1)

I searched the file system with find, and two other man pages were modified as well (but nothing else).

What could be the reason for this? Could it be the cache of unionfs, and if so,
how do I disable it?
Some (un)related questions:

1.) Should I use -o readdir_ino,use_ino? After compiling, testing and stracing (!) glibc,
     I've noticed that the inode field of structs returned from readdir and the like are set
     to -1, which breaks some fundamental unit tests in glibc.
2.) When compiling and testing glibc in a unified file system, I noticed that neither shm
     nor fifos work on unionfs. Can I mount a tmpfs on top of unionfs? Why are fifos made
     as regular files?
3.) Should I use -o chroot=.... instead of using chroot itself. I've read that file accesses
     outside unionfs can lead to cache inconsistency, but what does "outside unionfs"
     mean here?

Regards,
Winston
```

**Comment by arcivanov** [comment]
Any progress on this one? 

I'm using unionfs with ephemeral build host (tmpfs over readonly root) and because COW didn't work (another bug you filed) I had to mount over individual directories instead as well as using bind and rbind.

What I noticed was, RPM DB files wouldn't actually work through unionfs (corruption) unless rpmdb was recreated after unionfs mount overlay.

Any help I can provide with logging?

**Comment by arcivanov** [comment]
FS also gets stuck

[ 2337.848607] ------------[ cut here ]------------
[ 2337.850887] WARNING: CPU: 1 PID: 10 at kernel/workqueue.c:829 wq_worker_waking_up+0x53/0x70()
[ 2337.852519] Modules linked in: fuse ipv6 binfmt_misc dm_mod evbug evdev i2c_piix4 psmouse i2c_core button ext4 crc16 jbd2 mbcache
[ 2337.852519] CPU: 1 PID: 10 Comm: migration/1 Not tainted 3.14.34-27.48.amzn1.x86_64 #1
[ 2337.852519] Hardware name: Xen HVM domU, BIOS 4.2.amazon 12/03/2014
[ 2337.852519]  0000000000000009 ffff8807666a5c48 ffffffff81486605 0000000000000000
[ 2337.852519]  ffff8807666a5c80 ffffffff8105d33d 0000000000000000 ffff88078fc127c0
[ 2337.852519]  ffff88076638530a 0000000000000004 0000000000000000 ffff8807666a5c90
[ 2337.852519] Call Trace:
[ 2337.852519]  [<ffffffff81486605>] dump_stack+0x45/0x56
[ 2337.852519]  [<ffffffff8105d33d>] warn_slowpath_common+0x7d/0xa0
[ 2337.852519]  [<ffffffff8105d41a>] warn_slowpath_null+0x1a/0x20
[ 2337.852519]  [<ffffffff8107a1f3>] wq_worker_waking_up+0x53/0x70
[ 2337.852519]  [<ffffffff8108e450>] ttwu_do_activate.constprop.100+0x50/0x70
[ 2337.852519]  [<ffffffff81090df2>] try_to_wake_up+0x1d2/0x2c0
[ 2337.852519]  [<ffffffff81090f52>] default_wake_function+0x12/0x20
[ 2337.852519]  [<ffffffff810a2e28>] __wake_up_common+0x58/0x90
[ 2337.852519]  [<ffffffff8108ea10>] ? __migrate_task+0x170/0x170
[ 2337.852519]  [<ffffffff810a2e73>] __wake_up_locked+0x13/0x20
[ 2337.852519]  [<ffffffff810a3607>] complete+0x37/0x50
[ 2337.852519]  [<ffffffff810e196d>] cpu_stop_signal_done+0x2d/0x30
[ 2337.852519]  [<ffffffff810e1d80>] cpu_stopper_thread+0x90/0x130
[ 2337.852519]  [<ffffffff81489253>] ? __schedule+0x333/0x770
[ 2337.852519]  [<ffffffff810872af>] smpboot_thread_fn+0xff/0x1b0
[ 2337.852519]  [<ffffffff810871b0>] ? SyS_setgroups+0x180/0x180
[ 2337.852519]  [<ffffffff810801a2>] kthread+0xd2/0xf0
[ 2337.852519]  [<ffffffff810800d0>] ? kthread_create_on_node+0x180/0x180
[ 2337.852519]  [<ffffffff81495ffc>] ret_from_fork+0x7c/0xb0
[ 2337.852519]  [<ffffffff810800d0>] ? kthread_create_on_node+0x180/0x180
[ 2337.852519] ---[ end trace bda73d3a5f5219a1 ]---

**Comment by rpodgorny** [comment]
hi! unfortunately no progress here. this was just a dump from email i got long time ago and i wasn't really sure whether its still relevant or not. ...so i looks like it is. ;-)

anyway, what would help the most for now is if you posted the exact (and most simple) example that triggers the problem so i can extend the automated test suite and we can start catching this...

**Comment by rpodgorny** [comment]
btw, the stack trace you posted seems unrelated as it's a kernel problem.

**Comment by arcivanov** [comment]
Rgr. I will try to provide a distilled test case. Unfortunately, one of the problems that the system is for now proprietary.

**Comment by arcivanov** [comment]
I am aware the stack trace is kernel one. But the pattern is very clear:
# fuse-unionfs is mounted
# heavy IO virtually exclusively through unionfs is performed
# system grinds to a halt (Amazon EC2), this kernel stack trace can be observed on reboot

**Comment by arcivanov** [comment]
I'm running fuse-unionfs-0.26-1.el7.rf.x86_64.rpm from http://pkgs.repoforge.org/fuse-unionfs/
BTW, do you know if 1.0 is being planned for uptake by RH?

**Comment by arcivanov** [comment]
While I create clean room reproducible configuration, is there any debug logging I can collect in the wild that may help diagnose the problem?

**Comment by rpodgorny** [comment]
moved the kernel crash to a separate issue: https://github.com/rpodgorny/unionfs-fuse/issues/12

**Comment by rpodgorny** [comment]
not for now, i just need something i'm able to replicate on my systems. thanks.

**Comment by arcivanov** [comment]
Couple of quick questions:
1. What's the best way to get in touch with you interactively (Skype? IRC? GTalk?)
2. Would you be able to use AWS EC2 images as a test case?

**Comment by rpodgorny** [comment]
well, my response times are horrible most of the time, but feel free to try gtalk radekpodgorny@gmail.com or just plain email radek@podgorny.cz.

as for the images, not really sure, i don't have any experience with ec2. ;-) ...can it be used outside aws?

**Comment by arcivanov** [comment]
Hmm, I might just spin up an EC2 image for you and then give you SSH access to it then.

**Comment by arcivanov** [comment]
Sorry it's been so long. Nowadays I have trouble reproducing this problem on AWS with m4 and latest kernel. I have tried both t2.large and m4.2xlarge and I was not able to reproduce a lock up and RPMDB inconsistency. Either something changed in concurrency semantics or fuse module fixes percolated into AWS Linux.

**Comment by rpodgorny** [comment]
closing this for being stale. feel free to reopen.
