### ISSUE TITLE
Spurious "Got ioctl: ..." messages

### ISSUE THREAD

**Issue by lvml** [rpodgorny/unionfs-fuse#74]
unionfs-fuse/src/fuse_ops.c contains the line
```
fprintf(stderr, "Got ioctl: %d\n", cmd);
```
which emits a message whenever some application tries to perform some ioctl() on a file opened via unionfs-fuse.

This is disturbing, for example when running a script stored on a unionfs, because bash will by default try a "TCGETS" on every opened script file - resulting in numerous "Got ioctl: ..." messages emitted to the terminal.

Can you remove this line (or enable it only for debugging)?

**Comment by rpodgorny** [comment]
please try current master and reopen if you find any bug or it's not doing what you wanted...

**Comment by lvml** [comment]
(Works for me with latest git master.)
