### ISSUE TITLE
v2.0 debian package and/or xattr support

### ISSUE THREAD

**Issue by t3spe** [rpodgorny/unionfs-fuse#81]
For a [project I'm working on](https://github.com/cattlepi/cattlepi/issues/8) I would need v2.0 w/ XATTR support for ARM (Raspbian / Raspberry Pi)
The version that made its way into Raspbian is 1.0 and seems it was build w/o support for XATTR. Do you have any guidance on how to get the latest version in and/or build 2.0 w/ xattr support? Would just running make w/ latest source on a Raspberry Pi produce release binaries that have XATTR support? (I have tried this and it l looks like it's the case but I'm wondering if I'm missing something)

/cc @aakefbs name match on maintainer of the package :)

what i see on my pi:
**apt-cache show unionfs-fuse**
Package: unionfs-fuse
Version: 1.0-1
Architecture: armhf
Maintainer: Bernd Schubert <bernd.schubert@fastmail.fm>
Installed-Size: 101
Depends: libc6 (>= 2.7), libfuse2 (>= 2.8), fuse
Homepage: https://github.com/rpodgorny/unionfs-fuse
Priority: optional
Section: misc
Filename: pool/main/u/unionfs-fuse/unionfs-fuse_1.0-1_armhf.deb
Size: 40830
SHA256: acc5e45e1d2f67c981e25d8f24db776f884c6c766291edccfa0a9fb02037f3dd
SHA1: 73800c0c643cfbc9523077840e72c39efb4fd1af
MD5sum: bda1894516bc11a6b87f6f7140f0940d
Description: Fuse implementation of unionfs
 This is another unionfs implementation using filesystem in
 userspace (fuse).
Description-md5: 3cf52592fe13c3064499e6556589fea2

**Comment by rpodgorny** [comment]
several years and versions later - is this still relevant, @t3spe ?

**Comment by rpodgorny** [comment]
hmm, seems like this has been solved already: https://github.com/cattlepi/cattlepi/pull/9 ...closing, feel free to reopen.
