### ISSUE TITLE
Why the duplicity of CMakeLists.txt and Makefiles?

### ISSUE THREAD

**Issue by cesss** [rpodgorny/unionfs-fuse#86]
Are you supposed to build unionfs-fuse with CMake or with make? Why the duplicity? (at first glance it seems that the Makefiles are more updated than the CMakeLists)

**Comment by rpodgorny** [comment]
that is a relict from the time we've been playing with cmake. there's some logic implemented to allow for builds on other systems (macos, with/without xattrs) and so on... i personally build unionfs-fuse with plain make but i've left the cmake stuff in just in case anyone uses it (on systems i don't have).

anyway, i agree this is highly confusing and maybe we should pick just one. any suggestions?

**Comment by aakefbs** [comment]
I think there are still problems with builds on BSD/MACOS and also think that we have reached the limit of what we can do with plain Makefiles and ifdefs the location of the includes. Anything further requires tests in the build system to figure out the right include paths. Although I tempt a bit to replace cmake with the more easy to read meson syntax.

**Comment by rpodgorny** [comment]
bernd, you're - as always - more than welcome to submit any change you see fit to improve things. i'll most likely merge it right away. also, i'm quite eager to discover what this meson thing can offer (judging from the wikipedia article)... ;-)

**Comment by cesss** [comment]
Although I asked for the reason about the CMake/Makefiles duplicity, however, I think I really opened this issue because there's no "How to build unionfs-fuse" section at the Readme. If there was such a section, explaining if it's possible to use both systems, or if at this moment one is preferred over the other, I think I wouldn't have opened this issue :-)

Regarding Meson, a number of projects are migrating to it. I'm an old-fashioned "standard make"-based developer, and only recently I considered learning either CMake or Meson. I opted for CMake, just because I consider Python as a package that will be installed in a system at a very late stage of its design: when I'm building a system from scratch, I have a cross-compiler, very basic and primitive UNIX tools, and that's all. I also realized that most of the people use CMake in the wrong way, by copying CMakeLists from other projects and tuning them without even understanding the syntax (and these CMakeLists usually inherit old-style CMake that it's no longer the recommended way for doing things... newer CMake versions offer a better style). I found [a book](https://crascit.com/professional-cmake/)  that covers the "new style CMake", and I'm learning with it. I'm not trying to influence your decision, but given that I had to make the CMake vs Meson choice very recently, I thought it was wise to share my findings.

**Comment by rpodgorny** [comment]
so, the cmake flow and documentation has been updated. it will be included in "soon to be released" 3.0 version. #110 

closing, feel free to reopen.

**Comment by eli-schwartz** [comment]
> I opted for CMake, just because I consider Python as a package that will be installed in a system at a very late stage of its design: when I'm building a system from scratch, I have a cross-compiler, very basic and primitive UNIX tools, and that's all.

FWIW: https://mesonbuild.com/FAQ.html#but-i-really-want-a-version-of-meson-that-doesnt-use-python

https://sr.ht/~lattis/muon is a c99 port of meson that has continually increasing support of meson's build language and can already handle most of the common cases for a C/C++ project with custom_targets and no use of meson modules. Could be you'll find that interesting?

(CMake requires a C++11 compiler, which isn't typically hard but is definitely a significant requirement over c99, especially if you're doing self-hosted bootstrapping.)
