### ISSUE TITLE
Maximum value for max_files is 10240 (using osxfuse)

### ISSUE THREAD

**Issue by cesss** [rpodgorny/unionfs-fuse#88]
I tried to set max_files to 32768 as you do in your examples, but I get an error like this: "set_max_open_files: Setting the maximum number of files failed: Invalid argument".

By trial and error, I found that the maximum allowed amount for max_files is 10240.

Is this limit imposed by osxfuse or by MacOS? Can I increase it?

Note: I'm using the latest osxfuse version.

**Comment by JamaicanMoose** [comment]
It seems that this is a limitation imposed by macOS. See [here](https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1).

**Comment by rpodgorny** [comment]
> It seems that this is a limitation imposed by macOS. See [here](https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1). [This](https://wilsonmar.github.io/maximum-limits/) may also help.

thank you for the information! i'm not a mac user myself so i had no idea. i guess this can be closed now...
