### ISSUE TITLE
In macOS, copying files to the union filesystem using Finder fails with error code -50

### ISSUE THREAD

**Issue by briankendall** [rpodgorny/unionfs-fuse#92]
I built and installed the latest relase of unionfs-fuse in macOS 10.12.6. With it I'm able to mount union file systems and can interact with them using the command line successfully. However, it's not working properly with Finder. If I try to copy a file into the root of the union filesystem, it fails with error type -50, and the file is created in the correct location but contains no data. I haven't found any options I can use when mounting the filesystem that solves this.

In case it helps, I tried running `unionfs` with `-d` and attempted copying a file again. I've copied this output it printed into unionfs_output.txt and attached it to this post.
[unionfs_output.txt](https://github.com/rpodgorny/unionfs-fuse/files/4250960/unionfs_output.txt)

**Comment by aakefbs** [comment]
I'm not sure which file you are trying. Can you please correlate to your output? There are multiple acess() failure (permission denied - 13) - that *might* be your issue. You could try to deactivate the access method 

struct fuse_operations unionfs_oper = {
    .chmod = unionfs_chmod,
    .chown = unionfs_chown,
    .create = unionfs_create,
    .flush = unionfs_flush,
    .fsync = unionfs_fsync,
    .getattr = unionfs_getattr,
    .access = unionfs_access, ===> comment out this line


The current unionfs_access() function totally ignores supplementary groups and is therefore incomplete and might cause more issues than it solved.

**Comment by briankendall** [comment]
@aakefbs Per your request I've found a way to get cleaner output. This time the unionfs filesystem is comprised of two empty folders, the file being copied is named `___COPIED___`, and I'm using AppleScript to instruct the Finder to copy the file into the unionfs filesystem without having a Finder window open. This limits the output to just what's related to that single attempt at copying a file, and removes irrelevant output caused by Finder refreshing its view of the folder and other unrelated actions like that.
[unionfs_cleaner_output.txt](https://github.com/rpodgorny/unionfs-fuse/files/4252252/unionfs_cleaner_output.txt)

**Comment by briankendall** [comment]
I also tried commenting out the line you suggested and recompiling, but unfortunately that doesn't work around the issue.

**Comment by aakefbs** [comment]
access /___COPIED___ 01
   unique: 11, error: -13 (Permission denied), outsize: 16
unique: 11, opcode: GETXATTR (22), nodeid: 13, insize: 77, pid: 1537
getxattr /___COPIED___ com.apple.FinderInfo 32 0
   unique: 11, error: -93 (Attribute not found), outsize: 16
unique: 11, opcode: GETXATTR (22), nodeid: 13, insize: 79, pid: 1537
getxattr /___COPIED___ com.apple.ResourceFork 0 0
   unique: 11, error: -93 (Attribute not found), outsize: 16

Under which UID do you run this? If not as root (uid=0), can you add '-o relaxed_permissions' to your parameters? Also, how does the debug output look like, if you remove the access method (comment it out)? And finally, try to disable xattr - if you compile with cmake, it has. (Side note for myself, I need to update CMakeLists.txt to cmake3 - need to find the time).

**Comment by briankendall** [comment]
> Under which UID do you run this?

I'm running it under the system's normal user account, UID 501. As an experiment I tried running as root and got the same error.

> If not as root (uid=0), can you add '-o relaxed_permissions' to your parameters?

I've already tried relaxed_permissions and it doesn't fix it.

In case it's relevant, the folders that make up the unionfs filesystem's branches, as well as any files inside of it, all have the correct owner and permissions, which is to say owned by UID 501 and with permissions 644 or 755. I don't have any issues accessing, copying, or moving the files via the terminal.

> Also, how does the debug output look like, if you remove the access method (comment it out)?

See attached:
[unionfs_output_access_method_disabled.txt](https://github.com/rpodgorny/unionfs-fuse/files/4252598/unionfs_output_access_method_disabled.txt)

> And finally, try to disable xattr - if you compile with cmake, it has. 

I'm not using cmake to compile. Is there something in the code I can comment out or a precompiler macro I can change to disable xattr?

**Comment by briankendall** [comment]
Update: I found `DISABLE_XATTR` in the makefile and built with xattr disabled. That does indeed stop Finder from tossing an error when copying the file. Of course then the xattrs of these files won't be preserved properly.

Looking through the logs with an eye towards xattrs the one thing I notice is:

    unique: 16, opcode: SETXATTR (21), nodeid: 2, insize: 109, pid: 1688
    setxattr /___COPIED___ com.apple.FinderInfo 32 0x8 0
       unique: 16, error: -22 (Invalid argument), outsize: 16

I added an extra print to `unionfs_setxattr` in `fuse_ops.c` so that I could see precisely what arguments were being passed to `setxattr`, and found that when copying a file with Finder, `setxattr`'s flag argument was `XATTR_NOSECURITY`. With `cp` this was not the case; its flag parameter was 0.

Just as an experiment I added the following line to the top of `unionfs_setxattr`:

    flags = flags & (~XATTR_NOSECURITY);

With that in, I'm able to use Finder to copy files into the unionfs filesystem with no errors!

Now, with the significant caveats that I'm inexperienced with the nitty gritty of filesystems and this is the first time I've tinkered around with a fuse driver, it looks like it might actually be correct to unset the `XATTR_NOSECURITY` before calling `setxattr`. I'm basing this off of a) that the Darwin source code for `setxattr` always returns `EINVAL` if passed `XATTR_NOSECURITY` and b) that [another filesystem driver (glusterfs) also clears the `XATTR_NOSECURITY` flag](https://github.com/gluster/glusterfs/blob/master/libglusterfs/src/syscall.c#L503). Not that I'm a proponent of "monkey see monkey do" programming, but that at least gives this a little more credence.

What do you think? Is clearing `XATTR_NOSECURITY` a proper fix for this?

**Comment by aakefbs** [comment]
Hmm, it is a bit confusing the removing a flag that bypasses security checking makes it work. How does the Darwin code look like?

https://matt.ucc.asn.au/xnu/vfs/vfs_xattr.c

/*
 * Set the data of an extended attribute.
 */
int
vn_setxattr(vnode_t vp, const char *name, uio_t uio, int options, vfs_context_t context)
{
	int error;

	if (!(vp->v_type == VREG || vp->v_type == VDIR || vp->v_type == VLNK)) {
		return (EPERM);
	}
	if ((options & (XATTR_REPLACE|XATTR_CREATE)) == (XATTR_REPLACE|XATTR_CREATE)) {
		return (EINVAL);
	}
	if ((error = xattr_validatename(name))) {
		return (error);
	}
 	if (!(options & XATTR_NOSECURITY) && (error = vnode_authorize(vp, NULL, KAUTH_VNODE_WRITE_EXTATTRIBUTES, context)))
		goto out;

	/* The offset can only be non-zero for resource forks. */
	if (uio_offset(uio) != 0 && 
	    bcmp(name, XATTR_RESOURCEFORK_NAME, sizeof(XATTR_RESOURCEFORK_NAME)) != 0 ) {
		error = EINVAL;
		goto out;
	}

**Comment by briankendall** [comment]
The source code I was looking at was:

[https://opensource.apple.com/source/xnu/xnu-2050.22.13/bsd/vfs/vfs_syscalls.c](https://opensource.apple.com/source/xnu/xnu-2050.22.13/bsd/vfs/vfs_syscalls.c)

    /*
     * Set the data of an extended attribute.
     */
    int
    fsetxattr(proc_t p, struct fsetxattr_args *uap, int *retval)
    {
        vnode_t vp;
        char attrname[XATTR_MAXNAMELEN+1];
        uio_t auio = NULL;
        int spacetype = IS_64BIT_PROCESS(p) ? UIO_USERSPACE64 : UIO_USERSPACE32;
        size_t namelen;
        int error;
        char uio_buf[ UIO_SIZEOF(1) ];
    #if CONFIG_FSE
        vfs_context_t ctx = vfs_context_current();
    #endif

        if (uap->options & (XATTR_NOFOLLOW | XATTR_NOSECURITY | XATTR_NODEFAULT))
            return (EINVAL);

        if ((error = copyinstr(uap->attrname, attrname, sizeof(attrname), &namelen) != 0)) {
            return (error);
        }
        if (xattr_protected(attrname))
            return(EPERM);
        if (uap->size != 0 && uap->value == 0) {
            return (EINVAL);
        }
        if ( (error = file_vnode(uap->fd, &vp)) ) {
            return (error);
        }
        if ( (error = vnode_getwithref(vp)) ) {
            file_drop(uap->fd);
            return(error);
        }
        auio = uio_createwithbuffer(1, uap->position, spacetype, UIO_WRITE,
                                    &uio_buf[0], sizeof(uio_buf));
        uio_addiov(auio, uap->value, uap->size);

        error = vn_setxattr(vp, attrname, auio, uap->options, vfs_context_current());
    #if CONFIG_FSE
        if (error == 0) {
            add_fsevent(FSE_XATTR_MODIFIED, ctx,
                FSE_ARG_VNODE, vp,
                FSE_ARG_DONE);
        }
    #endif
        vnode_put(vp);
        file_drop(uap->fd);
        *retval = 0;
        return (error);
    }

Of particular note:

    if (uap->options & (XATTR_NOFOLLOW | XATTR_NOSECURITY | XATTR_NODEFAULT))
        return (EINVAL);

There's another clue I came across from [here](https://opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/vfs/vfs_xattr.c.auto.html) that has the comment:

    The XATTR_NOSECURITY flag implies a kernel request.

So I _think_ `XATTR_NOSECURITY` is meant to be used internally by the system, or something like that. Not sure why Finder is using it, but it wouldn't surprise me if Apple has set up Finder to have special privileges that allows it to use this flag, but other processes including fuse aren't allowed.

**Comment by aakefbs** [comment]
I'm not sure if 'Finder' really sets XATTR_NOSECURITY - we just need to keep in mind that fuse is a file system. So if the Apple vfs sets it internally for its internal handling, it would come up in fuse. Anyway the source code you are pointing to, clearly points out that this flag is not suitable for unionfs-fuse (or any other overlay) file system. The only way this flag would be useful, if a fuse-file system has its own on-disk format and in order to bypass security checks then.

**Comment by briankendall** [comment]
Want me to make a pull request?

With this fix I think there may be a few other Finder-related mac bugs to squash too that could be included in the same PR. (Assuming they are squashable -- Finder behaves in some weird ways which if we're unlucky may just be incompatible with unionfs.)

**Comment by rpodgorny** [comment]
that would be very nice of you since i don't have any macos device to do proper testing...

**Comment by briankendall** [comment]
Okay, I created #93. After adding in the `XATTR_NOSECURITY` fix I wasn't able to get any more strange errors to occur when manipulating files using Finder, so hopefully that means there aren't any more mac-specific fixes that are needed.

**Comment by briankendall** [comment]
I'm not sure if this is the best place to ask this -- I don't necessarily want to clutter up the thread with off-topic discussion -- but I was tinkering around with adding path preservation, i.e. trying to keep a file within the same RW branch during rename operations. I was thinking enabling it could be a UnionFS option, something like `-o path_preservation`.

If I were to implement this, would you want it added to the project, or is it out of scope? If it's in scope, I might be up for implementing it and creating another PR.

**Comment by rpodgorny** [comment]
> I'm not sure if this is the best place to ask this -- I don't necessarily want to clutter up the thread with off-topic discussion -- but I was tinkering around with adding path preservation, i.e. trying to keep a file within the same RW branch during rename operations. I was thinking enabling it could be a UnionFS option, something like `-o path_preservation`.
> 
> If I were to implement this, would you want it added to the project, or is it out of scope? If it's in scope, I might be up for implementing it and creating another PR.

do you mean this? https://github.com/rpodgorny/unionfs-fuse/issues/79

**Comment by briankendall** [comment]
> do you mean this? #79

Yup, forgot I could link to that issue.

**Comment by rpodgorny** [comment]
thank you for the pull request! i'll let it sit for a few days since i'm travelling right now and i can't really concentrate on things... ...and maybe bernd has something to say.

**Comment by xcorlett** [comment]
Any luck on all of this? Excited to see if it all works but don't want to mess with my fragile setup just yet.

**Comment by briankendall** [comment]
@robert-corlett Which thing are you referring to? The mac specific fixes or the path preserving feature?

**Comment by rpodgorny** [comment]
hi everyone! so as there were no objections and i have no means of testing this myself, i just decided to merge the fix and wait for possible bugreports from other mac users. ;-)

sorry for the delay - i had to take care of my temporary long term covid-19 stay here in thailand.
